language: python

python:
  - "2.7"

before_install:
  - echo "Test"

install:
 - python setup.py install
 - pwd
 - whoami
 - ls -l
#  - pip install --user -r requirements.txt
 - pip install -r requirements.txt

# command to run tests
script:
 - python symbtools/tests/test_core.py
